# Generated by Django 4.2.2 on 2023-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='Mail',
            new_name='mail',
        ),
    ]
